source "http://rubygems.org"

gem 'curb', :git => 'https://github.com/taf2/curb.git', :ref => 'dceafcd931c4fb'
gem 'therubyracer'
gem 'nokogiri'
gem "ruby-progressbar"
gem "nestegg"

group :development do
  gem "ruby-debug19", :require => "ruby-debug"
end
